title: Nayea's Blog
description: My Personal Blog
author: Nayea OH
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/nayea
about: Junior Front-end-developer

baseurl: "/nayea.github.io"
url: "http://nayea.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
